# Generated by Django 4.2.5 on 2023-12-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
